
project:
  type: book
  output-dir: docs

book: 
  title: Image Processing for Remote Sensing
  reader-mode: true
  chapters:
    - index.qmd
    - part: Lesson 1
      chapters: 
        - lesson1-1-tidy.qmd        
        - lesson1-2-imagery.qmd

        
    - part: references.qmd
format: 
  html:
    number-depth: -1
    number-sections: false
    css: aux/style.css
    include-in-header:
      - aux/script.html
    
    
    
bibliography: aux/bibliography.bib
execute: 
  warning: false
  message: false
  echo: false
code-summary: ">"
freeze: true




