
project:
  type: book
  output-dir: docs

book: 
  title: Image Processing for Remote Sensing
  reader-mode: true
  chapters:
    - index.qmd
    - part: lesson1.qmd
      chapters: 
        - lesson1-1-tidy.qmd        
        - lesson1-2-imagery.qmd
        - lesson1-3-datatypes.qmd
        - lesson1-4-nodata.qmd
    - part: TBD
      chapters: 
        - lesson-n-m-operations.qmd
format: 
  html:
    number-depth: -1
    number-sections: false
    css: aux/style.css
bibliography: aux/bibliography.bib
execute: 
  warning: false
  message: false
  echo: false
code-summary: ">"
freeze: true




